### ISSUE TITLE
[Question] Best Datasets for advanced training

### ISSUE THREAD

**Issue by shubham190398** [huggingface/diffusion-models-class#25]
Hello. Thanks for this wonderful unit on Diffusion Models. Could you suggest some bigger datasets for more advanced training, as I would like to see how changing the UNet architecture can affect Training time with them.

**Comment by johnowhitaker** [comment]
The LSUN datasets are great, lots of images in a specific category. Can be a bit of a pain to download them sometimes though. I've put up the churches dataset (~120k images): https://huggingface.co/datasets/tglcourse/lsun_church_train which is smaller than some of the other categories but still large enough to be interesting.

**Comment by johnowhitaker** [comment]
Wikiart (https://huggingface.co/datasets/huggan/wikiart) is also quite fun, at ~80k images I think and very visually pleasing. Even a poorly trained model looks quite nice, so harder to visually assess quality but much more satisfying than scary-looking faces!

**Comment by shubham190398** [comment]
Thanks a lot @johnowhitaker . Quick question, if I wrote an article with a custom use-case and colab notebooks based on what I've learned here (and from other resources provided here), would providing a reference to this unit suffice, or is there some form of official citation that I should be aware of.

**Comment by johnowhitaker** [comment]
@shubham190398  Just linking to the unit is totally fine! Maybe tag @huggingface on Twitter when you share it and they can help amplify your work too :)
