### ISSUE TITLE
Certificate of participation

### ISSUE THREAD

**Issue by DiTo97** [huggingface/diffusion-models-class#33]
Is there a certificate of participation for those who attended all units of the class?

**Comment by lewtun** [comment]
Hi @DiTo97, we'll be giving a certificate to everyone who takes part in the DreamBooth Hackathon (the criteria being you train a model and push it to the leaderboard :))

**Comment by DiTo97** [comment]
Alright, thanks! Gotta train a model then :)

**Comment by DiTo97** [comment]
> Hi @DiTo97, we'll be giving a certificate to everyone who takes part in the DreamBooth Hackathon (the criteria being you train a model and push it to the leaderboard :))

Is it possible to have the certificate before Jan 31, @lewtun?

I would need it for some paperwork related to extra activities at work.
